service: quite-indexed

image: tonyyunker/quite-indexed

servers:
  web:
    - 143.198.120.204

proxy:
  app_port: 5174
  healthcheck:
    interval: 3
    path: /
    timeout: 3

registry:
  username: tonyyunker

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
